#!/bin/sh
# Google Router Direct: second 2.4GHz SSID with DIRECT internet (never proxied)
# + router hostname + Tehran timezone

# --- separate network for direct clients (own subnet, isolated from LAN) ---
uci -q set network.direct='interface'
uci -q set network.direct.proto='static'
uci -q set network.direct.ipaddr='192.168.11.1'
uci -q set network.direct.netmask='255.255.255.0'
uci -q set network.direct.delegate='0'

# --- DHCP on it ---
uci -q set dhcp.direct='dhcp'
uci -q set dhcp.direct.interface='direct'
uci -q set dhcp.direct.start='100'
uci -q set dhcp.direct.limit='150'
uci -q set dhcp.direct.leasetime='12h'

# --- firewall zone: internet yes, LAN no (consoles can't reach LAN devices) ---
uci -q set firewall.direct='zone'
uci -q set firewall.direct.name='direct'
uci -q set firewall.direct.input='ACCEPT'
uci -q set firewall.direct.output='ACCEPT'
uci -q set firewall.direct.forward='ACCEPT'
uci -q add_list firewall.direct.network='direct'
uci -q set firewall.fwd_direct_wan='forwarding'
uci -q set firewall.fwd_direct_wan.src='direct'
uci -q set firewall.fwd_direct_wan.dest='wan'

# --- second SSID on BOTH radios, same name, same 'direct' bridge ---
uci -q set wireless.wifinet_direct='wifi-iface'
uci -q set wireless.wifinet_direct.device='radio0'
uci -q set wireless.wifinet_direct.network='direct'
uci -q set wireless.wifinet_direct.mode='ap'
uci -q set wireless.wifinet_direct.ssid='Google Router Direct'
uci -q set wireless.wifinet_direct.encryption='none'
uci -q set wireless.wifinet_direct.disabled='0'

uci -q set wireless.wifinet_direct5='wifi-iface'
uci -q set wireless.wifinet_direct5.device='radio1'
uci -q set wireless.wifinet_direct5.network='direct'
uci -q set wireless.wifinet_direct5.mode='ap'
uci -q set wireless.wifinet_direct5.ssid='Google Router Direct'
uci -q set wireless.wifinet_direct5.encryption='none'
uci -q set wireless.wifinet_direct5.disabled='0'

# --- identity ---
uci -q set system.@system[0].hostname='Google'
uci -q set system.@system[0].zonename='Asia/Tehran'
uci -q set system.@system[0].timezone='IRST-3:30'

uci commit network
uci commit dhcp
uci commit firewall
uci commit wireless
uci commit system
exit 0
